steps:
- name: 'gcr.io/cloud-builders/yarn'
  args: ['install']
  dir: 'functions/autodeploy'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'cf-test', '--trigger-http', '--runtime', 'python37', '--entry-point', 'main', '--source', './src']
  dir: 'functions/autodeploy'
