steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'functions', 'deploy', '$_FUNCTION_NAME', '--trigger-http',
    '--runtime', 'python37',
    '--entry-point', 'main',
    '--source', 'https://source.developers.google.com/projects/$PROJECT_ID/repos/$_REPOSITORY/moveable-aliases/master/paths/src',
    '--region', '$_REGION'
  ]
  dir: 'functions/autodeploy'
